### ISSUE TITLE
Update to Mockito 4.5.1

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/edelta#429]

**Comment by LorenzoBettini** [comment]
In the edelta.maven.plugin we get this error:

```
Error:  Tests run: 9, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 17.019 s <<< FAILURE! - in edelta.maven.plugin.EdeltaMojoTest
Error:  testDebugLogging(edelta.maven.plugin.EdeltaMojoTest)  Time elapsed: 4.173 s  <<< ERROR!
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.IllegalStateException: Internal problem occurred, please report it. Mockito is unable to load the default implementation of class that is a part of Mockito distribution. Failed to load interface org.mockito.plugins.MockMaker
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.reflect.InvocationTargetException
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.ExceptionInInitializerError
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.SecurityException: class "javax.annotation.Nonnull"'s signer information does not match signer information of other classes in the same package
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)

Error:  testProjectWithErrorFailOnValidationErrorFalse(edelta.maven.plugin.EdeltaMojoTest)  Time elapsed: 0.11 s  <<< ERROR!
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testProjectWithErrorFailOnValidationErrorFalse(EdeltaMojoTest.java:146)
Caused by: java.lang.IllegalStateException: Internal problem occurred, please report it. Mockito is unable to load the default implementation of class that is a part of Mockito distribution. Failed to load interface org.mockito.plugins.MockMaker
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.reflect.InvocationTargetException
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.ExceptionInInitializerError
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.SecurityException: class "javax.annotation.Nonnull"'s signer information does not match signer information of other classes in the same package
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
```

**Comment by LorenzoBettini** [comment]
In the TP objenesis is now a runtime dependency of mockito 4.5.1

```xml
  <dependencies>
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy</artifactId>
      <version>1.12.9</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy-agent</artifactId>
      <version>1.12.9</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.objenesis</groupId>
      <artifactId>objenesis</artifactId>
      <version>3.2</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

while in 3.12.4 it was compile

```xml
  <dependencies>
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy</artifactId>
      <version>1.11.13</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy-agent</artifactId>
      <version>1.11.13</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.objenesis</groupId>
      <artifactId>objenesis</artifactId>
      <version>3.2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

**Comment by LorenzoBettini** [comment]
Closes by https://github.com/LorenzoBettini/edelta/pull/430
