### ISSUE TITLE
EdeltaInterpreterHelper should check for getRawType NPE

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/edelta#69]
In this code

```
public class EdeltaInterpreterHelper {

	private static Object defaultInstance = new Object();

	public Object safeInstantiate(JavaReflectAccess javaReflectAccess, EdeltaUseAs useAs) {
		JvmTypeReference typeRef = useAs.getType();
		if (typeRef == null) {
			return defaultInstance;
		}
		final Class<?> javaType = javaReflectAccess.getRawType(typeRef.getType());
		try {
			return javaType.newInstance();
		} catch (InstantiationException | IllegalAccessException e) {
			return defaultInstance;
		}
	}
```
The returned javaType could be null if the requested (and resolved JvmType type) cannot be loaded through the ClassLoader. This might happen when running the Edelta compiler using `xtext-maven-plugin`. In fact, currently, all the dependencies needed by the interpreter must be available when running `xtext-maven-plugin`. Such a NPE is not reported though in the current implementation of the interpreter, while it should (and we should provide a detailed explanation).

**Comment by LorenzoBettini** [comment]
This test throws an IllegalStateException:

```
	@Test
	def void testSafeInstantiateOfUnresolvedUseAsType() {
		'''
			use NonExistent as my
		'''.parse.useAsClauses.head => [
			assertEquals(
				Object,
				interpreterHelper.safeInstantiate(javaReflectAccess, it).class
			)
		]
	}
```

```
java.lang.IllegalStateException: Cannot resolve proxy: __synthetic0.edelta#|0
	at org.eclipse.xtext.common.types.util.JavaReflectAccess.getRawType(JavaReflectAccess.java:108)
	at edelta.interpreter.EdeltaInterpreterHelper.safeInstantiate(EdeltaInterpreterHelper.java:33)
	at edelta.tests.EdeltaInterpreterHelperTest.lambda$3(EdeltaInterpreterHelperTest.java:115)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at edelta.tests.EdeltaInterpreterHelperTest.testSafeInstantiateOfUnresolvedUseAsType(EdeltaInterpreterHelperTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```
